#!/usr/bin/env bash
# Description: Checks if inputted year is a leap year

if [ $# -ne 0 ]; then
   echo "Usage $(basename $0) year"
   exit 1
fi

if [[ $(($1 % 4)) == 0 && $(($1 % 100)) != 0 ]]; then
   echo "$1 is a leap year"
elif [[ $(($1 % 400)) == 0 ]]; then
   echo "$1 is a leap year"
else
   echo "$1 is not a leap year"
fi
